# Загородний Даниил КСиК-32

# Условие

In [1]:
import random, numpy as np
m_real = []
n = 11
for i in range(n):
    m_row = []
    for j in range(n):
        m_row.append(random.randint(-3, 3))
    m_real.append(m_row)

m_real = np.array(m_real)
print(m_real)

[[ 0 -1 -2 -3  1 -1 -2  0  1  3 -3]
 [ 1  1  2  3  1 -1 -1  2  1  1  1]
 [-2  3 -1  0  0  0 -2 -3 -2 -1  1]
 [-1 -2  0  1 -2  2 -1  0  0 -2  0]
 [ 3 -2  0  1 -2  1  3  0  2 -2 -1]
 [ 3  0  0  3  0 -1  3  3  2 -2  0]
 [ 2  3  1 -3 -2  0  1  2  0  1 -1]
 [ 1 -2 -3  3 -1 -3 -3 -1  2  0 -3]
 [-3  1 -1  2  3  3 -3 -3  2 -3  3]
 [-2  3  3 -3  3 -3  0 -1  2 -1 -3]
 [ 1 -3  3 -1 -2 -3  3 -3 -3  0  2]]


In [4]:
import random, numpy as np
m_real = []
n = 11
for i in range(1):
    m_row = []
    for j in range(n):
        m_row.append(random.randint(-3, 3))
    m_real.append(m_row)

m_real = np.array(m_real)
print(m_real)

[[-2 -3  0 -1 -1 -3 -3 -2 -3 -2  0]]


In [2]:
m_complex = []
n = 11
for i in range(n):
    m_row = []
    for j in range(n):
        x = complex(random.randint(-3, 3), random.randint(-3, 3))
        m_row.append(x)
    m_complex.append(m_row)
m_complex = np.array(m_complex)    
print(m_complex)

[[-3.-2.j -3.+3.j  0.-2.j -1.+1.j  1.-2.j  2.-3.j -2.+0.j  2.-3.j -3.+1.j
  -3.-1.j  1.+2.j]
 [ 2.+0.j  1.-1.j -2.+0.j  0.-2.j  0.+1.j  0.-2.j  2.+3.j  1.+3.j  0.-3.j
  -1.+1.j  2.-1.j]
 [ 3.-1.j -2.-1.j  3.+0.j -2.+1.j  1.+1.j -1.-2.j -3.+1.j  1.+1.j  3.+1.j
  -2.-1.j  1.+0.j]
 [ 2.+3.j  3.-3.j -3.-3.j  0.+1.j -3.-1.j  3.+0.j  1.+3.j  1.-1.j  0.-2.j
   0.+2.j -1.+2.j]
 [-2.+0.j  0.-3.j  1.-1.j  0.-3.j  3.-2.j -1.+0.j  0.-3.j -1.+1.j -3.-3.j
  -1.+2.j -2.+0.j]
 [-3.+0.j  2.+3.j  2.-1.j  1.-2.j  1.+2.j  0.-1.j -1.+0.j -2.+0.j  0.+2.j
   2.+0.j  3.+3.j]
 [ 0.+0.j  0.+2.j  2.+0.j  2.+1.j  1.-1.j -1.+3.j  0.-2.j -1.+2.j  2.-3.j
  -3.+0.j -3.+3.j]
 [-2.-1.j -3.+1.j  2.+1.j -1.-1.j  0.+1.j -1.+1.j -2.+2.j  3.+1.j  0.-3.j
   0.+2.j  0.-2.j]
 [-2.+2.j -3.-2.j  3.+3.j -1.-2.j -3.+3.j -3.+2.j -2.+3.j  0.+3.j  2.-2.j
   2.+2.j  2.-3.j]
 [-3.+1.j  1.+0.j -3.+1.j  2.-1.j  2.+3.j  0.+1.j -3.+0.j -3.+0.j  2.+3.j
   2.+3.j -2.+2.j]
 [ 2.+3.j  3.+2.j -1.+2.j  3.+3.j  1.-2.j  1.+2.j  0.-3.j -1.+0.j -2.+

In [7]:
m_complex = []
n = 11
for i in range(1):
    m_row = []
    for j in range(n):
        x = complex(random.randint(-3, 3), random.randint(-3, 3))
        m_row.append(x)
    m_complex.append(m_row)
m_complex = np.array(m_complex)    
print(m_complex)

[[-3.-1.j  0.+0.j  0.-2.j  0.+2.j -3.-2.j  0.+3.j  1.+3.j  0.+3.j -3.-3.j
   1.+0.j  0.+0.j]]


# Решение матриц методом обратной матрицы

In [15]:
import numpy as np 
A=np.array([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
 [ 1,  1,  2,  3,  1, -1, -1,  2, 1,  1,  1],
 [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
 [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
 [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
 [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
 [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
 [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
 [-3, 1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
 [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
 [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]]) #создание матрицы 
B=np.array([-2, -3,  0, -1, -1, -3, -3, -2, -3, -2,  0]) #создаю матрицу столбца свободных членов 
det = np.linalg.det(A) 
if det==0: 
 print ("Определитель матрицы равен нулю, система имеет бесконечно много решений") 
else: 
 a_inv = np.linalg.inv(A) 
X=np.dot(a_inv, B) 
print ("Решение системы:\n", X)


Решение системы:
 [-5.88513307  1.03017687 -1.2106021   2.03935101 -3.14047375 -0.19858595
  4.46550944 -0.82690894  2.8526776   4.14119824  0.22544664]


# Проверка

In [16]:
print("Проверка:") 
for i in range(11): 
    otv = A[i][0]*X[0] + A[i][1]*X[1] + A[i][2]*X[2] + A[i][3]*X[3]+ A[i][4]*X[4] + A[i][5]*X[5]+ A[i][6]*X[6]+ A[i][7]*X[7]+ A[i][8]*X[8]+ A[i][9]*X[9]+ A[i][10]*X[10]
    print(otv, B[i])

Проверка:
-1.999999999999995 -2
-3.0000000000000036 -3
-2.886579864025407e-15 0
-0.9999999999999973 -1
-1.0000000000000007 -1
-3.0000000000000018 -3
-3.0 -3
-1.9999999999999967 -2
-3.0000000000000036 -3
-1.9999999999999958 -2
-4.440892098500626e-16 0


# Метод обратной матрицы с комплексными числами

In [17]:
import numpy as np 
A=np.array([[-3.-2.j, -3.+3.j,  0.-2.j, -1.+1.j,  1.-2.j,  2.-3.j, -2.+0.j,  2.-3.j, -3.+1.j,
  -3.-1.j,  1.+2.j],
 [ 2.+0.j,  1.-1.j, -2.+0.j,  0.-2.j,  0.+1.j,  0.-2.j,  2.+3.j,  1.+3.j,  0.-3.j,
  -1.+1.j,  2.-1.j],
 [ 3.-1.j, -2.-1.j,  3.+0.j, -2.+1.j,  1.+1.j, -1.-2.j, -3.+1.j,  1.+1.j,  3.+1.j,
  -2.-1.j,  1.+0.j],
 [ 2.+3.j,  3.-3.j, -3.-3.j,  0.+1.j, -3.-1.j,  3.+0.j,  1.+3.j,  1.-1.j, 0.-2.j,
   0.+2.j, -1.+2.j],
 [-2.+0.j,  0.-3.j,  1.-1.j,  0.-3.j,  3.-2.j, -1.+0.j,  0.-3.j, -1.+1.j, -3.-3.j,  
  -1.+2.j, -2.+0.j],
 [-3.+0.j,  2.+3.j, 2.-1.j,  1.-2.j,  1.+2.j,  0.-1.j, -1.+0.j, -2.+0.j,  0.+2.j,
   2.+0.j,  3.+3.j],
 [ 0.+0.j,  0.+2.j,  2.+0.j,  2.+1.j,  1.-1.j, -1.+3.j,  0.-2.j, -1.+2.j,  2.-3.j,
  -3.+0.j, -3.+3.j],
 [-2.-1.j, -3.+1.j,  2.+1.j, -1.-1.j,  0.+1.j, -1.+1.j, -2.+2.j,  3.+1.j,  0.-3.j,
   0.+2.j,  0.-2.j],
 [-2.+2.j, -3.-2.j,  3.+3.j, -1.-2.j, -3.+3.j, -3.+2.j, -2.+3.j,  0.+3.j,  2.-2.j,
   2.+2.j,  2.-3.j],
 [-3.+1.j,  1.+0.j, -3.+1.j,  2.-1.j,  2.+3.j,  0.+1.j, -3.+0.j, -3.+0.j,  2.+3.j,
   2.+3.j, -2.+2.j],
 [ 2.+3.j,  3.+2.j, -1.+2.j,  3.+3.j,  1.-2.j,  1.+2.j,  0.-3.j, -1.+0.j, -2.+2.j,
   1.+3.j,  2.+3.j]]) #создание матрицы 
B=np.array([-3.-1.j, 0.+0.j,  0.-2.j,  0.+2.j, -3.-2.j,  0.+3.j,  1.+3.j,  0.+3.j, -3.-3.j,
   1.+0.j,  0.+0.j]) #создаю матрицу столбца свободных членов 
det = np.linalg.det(A) 
if det==0: 
 print ("Определитель матрицы равен нулю, система имеет бесконечно много решений") 
else: 
 a_inv = np.linalg.inv(A) 
X=np.dot(a_inv, B) 
print ("Решение системы:\n", X)



Решение системы:
 [ 1.72326265+0.19162439j  2.19894081-0.49677449j -1.79768889-1.07303601j
 -0.12919282+0.82240572j  0.07532908-1.20068416j -3.17332842-1.24936017j
 -3.27124596-0.59723819j  0.43508882+2.33494833j -1.82424066+2.09247407j
  0.13168118+2.89457982j -0.03742876-0.94661484j]


# Проверка комплексных чисел

In [18]:
print("Проверка:") 
for i in range(11): 
    otv = A[i][0]*X[0] + A[i][1]*X[1] + A[i][2]*X[2] + A[i][3]*X[3]+ A[i][4]*X[4] + A[i][5]*X[5]+ A[i][6]*X[6]+ A[i][7]*X[7]+ A[i][8]*X[8]+ A[i][9]*X[9]+ A[i][10]*X[10]
    print(otv, B[i])

Проверка:
(-3.0000000000000027-0.9999999999999998j) (-3-1j)
(-6.439293542825908e-15+1.5543122344752192e-15j) 0j
(3.566591466608315e-15-1.999999999999992j) -2j
(-1.5543122344752192e-15+1.999999999999996j) 2j
(-2.9999999999999973-2.000000000000001j) (-3-2j)
(3.1086244689504383e-15+3.0000000000000013j) 3j
(1.0000000000000047+3.0000000000000004j) (1+3j)
(3.774758283725532e-15+3j) 3j
(-3.000000000000002-2.9999999999999982j) (-3-3j)
(0.999999999999998-1.9984014443252818e-15j) (1+0j)
(4.884981308350689e-15+2.6645352591003757e-15j) 0j


# Решение матриц методом Краймера

In [19]:
import numpy as np
a=np.array([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
 [ 1,  1,  2,  3,  1, -1, -1,  2, 1,  1,  1],
 [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
 [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
 [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
 [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
 [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
 [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
 [-3, 1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
 [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
 [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])
b=np.array([-2, -3,  0, -1, -1, -3, -3, -2, -3, -2,  0])
det=np.linalg.det(a)
if det==0:
        print("Определитель матрицы равен нулю, система имеет бесконечно много решений")
else:
        s_0=a[:,0]
        s_1=a[:,1]
        s_2=a[:,2]
        s_3=a[:,3]
        s_4=a[:,4]
        s_5=a[:,5]
        s_6=a[:,6]
        s_7=a[:,7]
        s_8=a[:,8]
        s_9=a[:,9]
        s_10=a[:,10]
        
        a_1=np.column_stack((b,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_1 = np.linalg.det(a_1)
        
        a_2=np.column_stack((s_0,b,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_2 = np.linalg.det(a_2)
        
        a_3=np.column_stack((s_0,s_1,b,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_3 = np.linalg.det(a_3)
        
        a_4=np.column_stack((s_0,s_1,s_2,b,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_4 = np.linalg.det(a_4)
        
        a_5=np.column_stack((s_0,s_1,s_2,s_3,b,s_5,s_6,s_7,s_8,s_9,s_10))
        det_5 = np.linalg.det(a_5)
        
        a_6=np.column_stack((s_0,s_1,s_2,s_3,s_4,b,s_6,s_7,s_8,s_9,s_10))
        det_6 = np.linalg.det(a_6)
        
        a_7=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,b,s_7,s_8,s_9,s_10))
        det_7 = np.linalg.det(a_7)
        
        a_8=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,b,s_8,s_9,s_10))
        det_8 = np.linalg.det(a_8)
        
        a_9=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,s_7,b,s_9,s_10))
        det_9 = np.linalg.det(a_9)
        
        a_10=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,b,s_10))
        det_10 = np.linalg.det(a_10)
        
        a_11=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,b))
        det_11 = np.linalg.det(a_11)
        
        x_1=det_1/det
        x_2=det_2/det
        x_3=det_3/det
        x_4=det_4/det
        x_5=det_5/det
        x_6=det_6/det
        x_7=det_7/det
        x_8=det_8/det
        x_9=det_9/det
        x_10=det_10/det
        x_11=det_11/det
        
        print("x1 =", x_1)
        print("x2 =", x_2)
        print("x3 =", x_3)
        print("x4 =", x_4)
        print("x5 =", x_5)
        print("x6 =", x_6)
        print("x7 =", x_7)
        print("x8 =", x_8)
        print("x9 =", x_9)
        print("x10 =", x_10)
        print("x11 =", x_11)

x1 = -5.885133070761342
x2 = 1.030176873094234
x3 = -1.2106021005759635
x4 = 2.0393510115676885
x5 = -3.1404737488504875
x6 = -0.19858595300324283
x7 = 4.46550944412177
x8 = -0.8269089407579485
x9 = 2.8526775990997533
x10 = 4.141198241856627
x11 = 0.22544664464450007


# Проверка метода Крамера


In [22]:
print("Проверка:")
for i in range(11): 
    otv = a[i][0]*X[0] + a[i][1]*X[1] + a[i][2]*X[2] + a[i][3]*X[3]+ a[i][4]*X[4] + a[i][5]*X[5]+ a[i][6]*X[6]+ a[i][7]*X[7]+ a[i][8]*X[8]+ a[i][9]*X[9]+ a[i][10]*X[10]
    print(otv, b[i])

Проверка:
(10.258253984920193+15.03483980352023j) -2
(5.599340092787642+9.372244968620194j) -3
(13.664582869559464-14.63704764384503j) 0
(-9.739768495920638-3.664943169645177j) -1
(-16.369425870039418+1.0935247688183587j) -1
(-4.464777182989928+7.900369405860612j) -3
(6.250620752010059+5.6678935490047895j) -3
(17.617979438033295+18.301822163239496j) -2
(-6.372881630486997-18.255699432986475j) -3
(3.787816397914818-5.618604922438765j) -2
(-6.489246374746725-13.177328501250674j) 0


In [17]:
import numpy as np
a=np.array([[-3.-2.j, -3.+3.j,  0.-2.j, -1.+1.j,  1.-2.j,  2.-3.j, -2.+0.j,  2.-3.j, -3.+1.j,
  -3.-1.j,  1.+2.j],
 [ 2.+0.j,  1.-1.j, -2.+0.j,  0.-2.j,  0.+1.j,  0.-2.j,  2.+3.j,  1.+3.j,  0.-3.j,
  -1.+1.j,  2.-1.j],
 [ 3.-1.j, -2.-1.j,  3.+0.j, -2.+1.j,  1.+1.j, -1.-2.j, -3.+1.j,  1.+1.j,  3.+1.j,
  -2.-1.j,  1.+0.j],
 [ 2.+3.j,  3.-3.j, -3.-3.j,  0.+1.j, -3.-1.j,  3.+0.j,  1.+3.j,  1.-1.j, 0.-2.j,
   0.+2.j, -1.+2.j],
 [-2.+0.j,  0.-3.j,  1.-1.j,  0.-3.j,  3.-2.j, -1.+0.j,  0.-3.j, -1.+1.j, -3.-3.j,  
  -1.+2.j, -2.+0.j],
 [-3.+0.j,  2.+3.j, 2.-1.j,  1.-2.j,  1.+2.j,  0.-1.j, -1.+0.j, -2.+0.j,  0.+2.j,
   2.+0.j,  3.+3.j],
 [ 0.+0.j,  0.+2.j,  2.+0.j,  2.+1.j,  1.-1.j, -1.+3.j,  0.-2.j, -1.+2.j,  2.-3.j,
  -3.+0.j, -3.+3.j],
 [-2.-1.j, -3.+1.j,  2.+1.j, -1.-1.j,  0.+1.j, -1.+1.j, -2.+2.j,  3.+1.j,  0.-3.j,
   0.+2.j,  0.-2.j],
 [-2.+2.j, -3.-2.j,  3.+3.j, -1.-2.j, -3.+3.j, -3.+2.j, -2.+3.j,  0.+3.j,  2.-2.j,
   2.+2.j,  2.-3.j],
 [-3.+1.j,  1.+0.j, -3.+1.j,  2.-1.j,  2.+3.j,  0.+1.j, -3.+0.j, -3.+0.j,  2.+3.j,
   2.+3.j, -2.+2.j],
 [ 2.+3.j,  3.+2.j, -1.+2.j,  3.+3.j,  1.-2.j,  1.+2.j,  0.-3.j, -1.+0.j, -2.+2.j,
   1.+3.j,  2.+3.j]])
b=np.array([-3.-1.j, 0.+0.j,  0.-2.j,  0.+2.j, -3.-2.j,  0.+3.j,  1.+3.j,  0.+3.j, -3.-3.j,
   1.+0.j,  0.+0.j])
det=np.linalg.det(a)
if det==0:
        print("Определитель матрицы равен нулю, система имеет бесконечно много решений")
else:
        s_0=a[:,0]
        s_1=a[:,1]
        s_2=a[:,2]
        s_3=a[:,3]
        s_4=a[:,4]
        s_5=a[:,5]
        s_6=a[:,6]
        s_7=a[:,7]
        s_8=a[:,8]
        s_9=a[:,9]
        s_10=a[:,10]
        
        a_1=np.column_stack((b,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_1 = np.linalg.det(a_1)
        
        a_2=np.column_stack((s_0,b,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_2 = np.linalg.det(a_2)
        
        a_3=np.column_stack((s_0,s_1,b,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_3 = np.linalg.det(a_3)
        
        a_4=np.column_stack((s_0,s_1,s_2,b,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_4 = np.linalg.det(a_4)
        
        a_5=np.column_stack((s_0,s_1,s_2,s_3,b,s_5,s_6,s_7,s_8,s_9,s_10))
        det_5 = np.linalg.det(a_5)
        
        a_6=np.column_stack((s_0,s_1,s_2,s_3,s_4,b,s_6,s_7,s_8,s_9,s_10))
        det_6 = np.linalg.det(a_6)
        
        a_7=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,b,s_7,s_8,s_9,s_10))
        det_7 = np.linalg.det(a_7)
        
        a_8=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,b,s_8,s_9,s_10))
        det_8 = np.linalg.det(a_8)
        
        a_9=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,s_7,b,s_9,s_10))
        det_9 = np.linalg.det(a_9)
        
        a_10=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,b,s_10))
        det_10 = np.linalg.det(a_10)
        
        a_11=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,b))
        det_11 = np.linalg.det(a_11)
        
        x_1=det_1/det
        x_2=det_2/det
        x_3=det_3/det
        x_4=det_4/det
        x_5=det_5/det
        x_6=det_6/det
        x_7=det_7/det
        x_8=det_8/det
        x_9=det_9/det
        x_10=det_10/det
        x_11=det_11/det
        
        print("x1 =", x_1)
        print("x2 =", x_2)
        print("x3 =", x_3)
        print("x4 =", x_4)
        print("x5 =", x_5)
        print("x6 =", x_6)
        print("x7 =", x_7)
        print("x8 =", x_8)
        print("x9 =", x_9)
        print("x10 =", x_10)
        print("x11 =", x_11)

x1 = (1.7232626487107772+0.19162439218609814j)
x2 = (2.1989408114000346-0.49677449377741323j)
x3 = (-1.797688885923673-1.0730360114730026j)
x4 = (-0.12919281666547866+0.822405723927364j)
x5 = (0.07532907933355808-1.2006841550193836j)
x6 = (-3.1733284236859087-1.2493601722719057j)
x7 = (-3.2712459576910575-0.5972381944385831j)
x8 = (0.4350888169034058+2.334948326283931j)
x9 = (-1.824240660526162+2.092474069293538j)
x10 = (0.13168117969821144+2.8945798244373933j)
x11 = (-0.03742875916878426-0.9466148366144876j)


# Проверка решения матриц с комплексными числами методом Крамера

In [18]:
print("Проверка:") 
for i in range(11): 
    otv = a[i][0]*X[0] + a[i][1]*X[1] + a[i][2]*X[2] + a[i][3]*X[3]+ a[i][4]*X[4] + a[i][5]*X[5]+ a[i][6]*X[6]+ a[i][7]*X[7]+ a[i][8]*X[8]+ a[i][9]*X[9]+ a[i][10]*X[10]
    print(otv, b[i])

Проверка:
(-3.0000000000000027-0.9999999999999998j) (-3-1j)
(-6.439293542825908e-15+1.5543122344752192e-15j) 0j
(3.566591466608315e-15-1.999999999999992j) -2j
(-1.5543122344752192e-15+1.999999999999996j) 2j
(-2.9999999999999973-2.000000000000001j) (-3-2j)
(3.1086244689504383e-15+3.0000000000000013j) 3j
(1.0000000000000047+3.0000000000000004j) (1+3j)
(3.774758283725532e-15+3j) 3j
(-3.000000000000002-2.9999999999999982j) (-3-3j)
(0.999999999999998-1.9984014443252818e-15j) (1+0j)
(4.884981308350689e-15+2.6645352591003757e-15j) 0j


# LU-разложение

In [19]:
#Вычислите LU-разложение своих матриц (действительной и комплексной из Задания 01). Прямо проверьте правильность полученных результатов. 
import numpy as np
import scipy.linalg as la
M = np.array([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
 [ 1,  1,  2,  3,  1, -1, -1,  2, 1,  1,  1],
 [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
 [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
 [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
 [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
 [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
 [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
 [-3, 1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
 [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
 [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])
P, L, U = la.lu(M)
M

array([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
       [ 1,  1,  2,  3,  1, -1, -1,  2,  1,  1,  1],
       [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
       [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
       [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
       [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
       [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
       [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
       [-3,  1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
       [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
       [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])

In [20]:
P

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.66666667,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.33333333, -0.53846154,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.33333333,  0.38461538,  0.45652174,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        , -0.23076923, -0.5       , -0.9844358 ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.33333333, -0.30769231, -0.76086957, -0.17509728, -0.51026393,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.   

In [22]:
U

array([[ 3.        , -2.        ,  0.        ,  1.        , -2.        ,
         1.        ,  3.        ,  0.        ,  2.        , -2.        ,
        -1.        ],
       [ 0.        ,  4.33333333,  1.        , -3.66666667, -0.66666667,
        -0.66666667, -1.        ,  2.        , -1.33333333,  2.33333333,
        -0.33333333],
       [ 0.        ,  0.        ,  3.53846154, -3.30769231, -1.69230769,
        -3.69230769,  1.46153846, -1.92307692, -4.38461538,  1.92307692,
         2.15384615],
       [ 0.        ,  0.        ,  0.        ,  5.58695652,  2.69565217,
         0.60869565, -2.2826087 ,  2.10869565,  2.84782609, -0.10869565,
         0.47826087],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  2.6536965 ,
        -2.40077821, -3.74708171,  1.57587549,  1.30350195,  4.39299611,
        -1.52918288],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -7.46627566, -5.50733138, -0.6744868 , -1.24926686,  5.07038123,
        -1.826

# Проверка

In [23]:
#Проверка
M

array([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
       [ 1,  1,  2,  3,  1, -1, -1,  2,  1,  1,  1],
       [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
       [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
       [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
       [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
       [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
       [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
       [-3,  1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
       [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
       [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])

In [24]:
P.dot(L.dot(U))

array([[ 0.00000000e+00, -1.00000000e+00, -2.00000000e+00,
        -3.00000000e+00,  1.00000000e+00, -1.00000000e+00,
        -2.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         3.00000000e+00, -3.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         3.00000000e+00,  1.00000000e+00, -1.00000000e+00,
        -1.00000000e+00,  2.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00],
       [-2.00000000e+00,  3.00000000e+00, -1.00000000e+00,
        -1.23904627e-16, -1.19944676e-17,  8.52540223e-18,
        -2.00000000e+00, -3.00000000e+00, -2.00000000e+00,
        -1.00000000e+00,  1.00000000e+00],
       [-1.00000000e+00, -2.00000000e+00,  2.32070030e-17,
         1.00000000e+00, -2.00000000e+00,  2.00000000e+00,
        -1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.00000000e+00,  0.00000000e+00],
       [ 3.00000000e+00, -2.00000000e+00,  0.00000000e+00,
         1.00000000e+00, -2.00000000e+00,  1.00000000e+00,
  

# LU разложение матрицы с комплексными числами 


In [25]:
import numpy as np
import scipy.linalg as la
M = np.array([[-3.-2.j, -3.+3.j,  0.-2.j, -1.+1.j,  1.-2.j,  2.-3.j, -2.+0.j,  2.-3.j, -3.+1.j,
  -3.-1.j,  1.+2.j],
 [ 2.+0.j,  1.-1.j, -2.+0.j,  0.-2.j,  0.+1.j,  0.-2.j,  2.+3.j,  1.+3.j,  0.-3.j,
  -1.+1.j,  2.-1.j],
 [ 3.-1.j, -2.-1.j,  3.+0.j, -2.+1.j,  1.+1.j, -1.-2.j, -3.+1.j,  1.+1.j,  3.+1.j,
  -2.-1.j,  1.+0.j],
 [ 2.+3.j,  3.-3.j, -3.-3.j,  0.+1.j, -3.-1.j,  3.+0.j,  1.+3.j,  1.-1.j, 0.-2.j,
   0.+2.j, -1.+2.j],
 [-2.+0.j,  0.-3.j,  1.-1.j,  0.-3.j,  3.-2.j, -1.+0.j,  0.-3.j, -1.+1.j, -3.-3.j,  
  -1.+2.j, -2.+0.j],
 [-3.+0.j,  2.+3.j, 2.-1.j,  1.-2.j,  1.+2.j,  0.-1.j, -1.+0.j, -2.+0.j,  0.+2.j,
   2.+0.j,  3.+3.j],
 [ 0.+0.j,  0.+2.j,  2.+0.j,  2.+1.j,  1.-1.j, -1.+3.j,  0.-2.j, -1.+2.j,  2.-3.j,
  -3.+0.j, -3.+3.j],
 [-2.-1.j, -3.+1.j,  2.+1.j, -1.-1.j,  0.+1.j, -1.+1.j, -2.+2.j,  3.+1.j,  0.-3.j,
   0.+2.j,  0.-2.j],
 [-2.+2.j, -3.-2.j,  3.+3.j, -1.-2.j, -3.+3.j, -3.+2.j, -2.+3.j,  0.+3.j,  2.-2.j,
   2.+2.j,  2.-3.j],
 [-3.+1.j,  1.+0.j, -3.+1.j,  2.-1.j,  2.+3.j,  0.+1.j, -3.+0.j, -3.+0.j,  2.+3.j,
   2.+3.j, -2.+2.j],
 [ 2.+3.j,  3.+2.j, -1.+2.j,  3.+3.j,  1.-2.j,  1.+2.j,  0.-3.j, -1.+0.j, -2.+2.j,
   1.+3.j,  2.+3.j]])
P, L, U = la.lu(M)
M

array([[-3.-2.j, -3.+3.j,  0.-2.j, -1.+1.j,  1.-2.j,  2.-3.j, -2.+0.j,
         2.-3.j, -3.+1.j, -3.-1.j,  1.+2.j],
       [ 2.+0.j,  1.-1.j, -2.+0.j,  0.-2.j,  0.+1.j,  0.-2.j,  2.+3.j,
         1.+3.j,  0.-3.j, -1.+1.j,  2.-1.j],
       [ 3.-1.j, -2.-1.j,  3.+0.j, -2.+1.j,  1.+1.j, -1.-2.j, -3.+1.j,
         1.+1.j,  3.+1.j, -2.-1.j,  1.+0.j],
       [ 2.+3.j,  3.-3.j, -3.-3.j,  0.+1.j, -3.-1.j,  3.+0.j,  1.+3.j,
         1.-1.j,  0.-2.j,  0.+2.j, -1.+2.j],
       [-2.+0.j,  0.-3.j,  1.-1.j,  0.-3.j,  3.-2.j, -1.+0.j,  0.-3.j,
        -1.+1.j, -3.-3.j, -1.+2.j, -2.+0.j],
       [-3.+0.j,  2.+3.j,  2.-1.j,  1.-2.j,  1.+2.j,  0.-1.j, -1.+0.j,
        -2.+0.j,  0.+2.j,  2.+0.j,  3.+3.j],
       [ 0.+0.j,  0.+2.j,  2.+0.j,  2.+1.j,  1.-1.j, -1.+3.j,  0.-2.j,
        -1.+2.j,  2.-3.j, -3.+0.j, -3.+3.j],
       [-2.-1.j, -3.+1.j,  2.+1.j, -1.-1.j,  0.+1.j, -1.+1.j, -2.+2.j,
         3.+1.j,  0.-3.j,  0.+2.j,  0.-2.j],
       [-2.+2.j, -3.-2.j,  3.+3.j, -1.-2.j, -3.+3.j, -3.+2.j, -2.+3.j,
 

In [26]:
P

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
L

array([[ 1.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j],
       [ 0.15384615-7.69230769e-01j,  1.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j],
       [-0.92307692-3.84615385e-01j,  0.23960067+4.99168053e-02j,
         1.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j,


In [28]:
U

array([[ -3.        -2.j        ,  -3.        +3.j        ,
          0.        -2.j        ,  -1.        +1.j        ,
          1.        -2.j        ,   2.        -3.j        ,
         -2.        +0.j        ,   2.        -3.j        ,
         -3.        +1.j        ,  -3.        -1.j        ,
          1.        +2.j        ],
       [  0.        +0.j        ,  -4.84615385-4.76923077j,
          4.53846154+3.30769231j,  -1.61538462-2.92307692j,
         -1.61538462+4.07692308j,  -1.        +4.j        ,
         -1.69230769+1.46153846j,   2.        +5.j        ,
          1.69230769-4.46153846j,   3.23076923-0.15384615j,
          0.30769231-2.53846154j],
       [  0.        +0.j        ,   0.        +0.j        ,
         -3.1530782 -5.86522463j,  -1.06655574+2.31946755j,
         -0.7171381 -3.3577371j ,   6.43926789-2.90848586j,
         -0.36772047+1.96505824j,   3.7703827 -4.29783694j,
         -3.78202995-1.24625624j,  -3.16638935-0.20133111j,
         -1.04658902+4.8236272

In [29]:
#Проверка
M

array([[-3.-2.j, -3.+3.j,  0.-2.j, -1.+1.j,  1.-2.j,  2.-3.j, -2.+0.j,
         2.-3.j, -3.+1.j, -3.-1.j,  1.+2.j],
       [ 2.+0.j,  1.-1.j, -2.+0.j,  0.-2.j,  0.+1.j,  0.-2.j,  2.+3.j,
         1.+3.j,  0.-3.j, -1.+1.j,  2.-1.j],
       [ 3.-1.j, -2.-1.j,  3.+0.j, -2.+1.j,  1.+1.j, -1.-2.j, -3.+1.j,
         1.+1.j,  3.+1.j, -2.-1.j,  1.+0.j],
       [ 2.+3.j,  3.-3.j, -3.-3.j,  0.+1.j, -3.-1.j,  3.+0.j,  1.+3.j,
         1.-1.j,  0.-2.j,  0.+2.j, -1.+2.j],
       [-2.+0.j,  0.-3.j,  1.-1.j,  0.-3.j,  3.-2.j, -1.+0.j,  0.-3.j,
        -1.+1.j, -3.-3.j, -1.+2.j, -2.+0.j],
       [-3.+0.j,  2.+3.j,  2.-1.j,  1.-2.j,  1.+2.j,  0.-1.j, -1.+0.j,
        -2.+0.j,  0.+2.j,  2.+0.j,  3.+3.j],
       [ 0.+0.j,  0.+2.j,  2.+0.j,  2.+1.j,  1.-1.j, -1.+3.j,  0.-2.j,
        -1.+2.j,  2.-3.j, -3.+0.j, -3.+3.j],
       [-2.-1.j, -3.+1.j,  2.+1.j, -1.-1.j,  0.+1.j, -1.+1.j, -2.+2.j,
         3.+1.j,  0.-3.j,  0.+2.j,  0.-2.j],
       [-2.+2.j, -3.-2.j,  3.+3.j, -1.-2.j, -3.+3.j, -3.+2.j, -2.+3.j,
 

In [30]:
P.dot(L.dot(U))

array([[-3.00000000e+00-2.00000000e+00j, -3.00000000e+00+3.00000000e+00j,
         0.00000000e+00-2.00000000e+00j, -1.00000000e+00+1.00000000e+00j,
         1.00000000e+00-2.00000000e+00j,  2.00000000e+00-3.00000000e+00j,
        -2.00000000e+00+0.00000000e+00j,  2.00000000e+00-3.00000000e+00j,
        -3.00000000e+00+1.00000000e+00j, -3.00000000e+00-1.00000000e+00j,
         1.00000000e+00+2.00000000e+00j],
       [ 2.00000000e+00+0.00000000e+00j,  1.00000000e+00-1.00000000e+00j,
        -2.00000000e+00-1.11022302e-16j, -1.11022302e-16-2.00000000e+00j,
         1.11022302e-16+1.00000000e+00j, -4.44089210e-16-2.00000000e+00j,
         2.00000000e+00+3.00000000e+00j,  1.00000000e+00+3.00000000e+00j,
         0.00000000e+00-3.00000000e+00j, -1.00000000e+00+1.00000000e+00j,
         2.00000000e+00-1.00000000e+00j],
       [ 3.00000000e+00-1.00000000e+00j, -2.00000000e+00-1.00000000e+00j,
         3.00000000e+00+2.22044605e-16j, -2.00000000e+00+1.00000000e+00j,
         1.00000000e+00+1.00

# QR-разложение матриц с действительными числами

In [31]:
#Вычислите QR-разложение своих матриц (действительной и комплексной из Задания 01). Проверьте правильность полученных результатов. 
A = np.matrix([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
 [ 1,  1,  2,  3,  1, -1, -1,  2, 1,  1,  1],
 [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
 [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
 [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
 [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
 [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
 [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
 [-3, 1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
 [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
 [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])
q, r = np.linalg.qr(A)
A

matrix([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
        [ 1,  1,  2,  3,  1, -1, -1,  2,  1,  1,  1],
        [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
        [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
        [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
        [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
        [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
        [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
        [-3,  1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
        [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
        [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])

In [32]:
q

matrix([[ 0.        ,  0.15027985, -0.29728314,  0.54327681,  0.43086928,
          0.05461531, -0.32359152, -0.07823869, -0.0881639 , -0.36943543,
         -0.38751731],
        [-0.15249857, -0.20969282,  0.27028948, -0.51959111,  0.15641989,
          0.08539434, -0.64309639, -0.01327254, -0.24261019,  0.05347871,
         -0.28725181],
        [ 0.30499714, -0.33201362, -0.2298872 , -0.093068  , -0.43857711,
          0.28780176,  0.23405305, -0.32398858, -0.17360548, -0.1204938 ,
         -0.50561561],
        [ 0.15249857,  0.35997267,  0.10426964, -0.10247753, -0.47759132,
         -0.16526612, -0.25371447,  0.34310256,  0.44217656, -0.35596346,
         -0.25702763],
        [-0.45749571,  0.12232081, -0.00370501, -0.00773474, -0.00966466,
         -0.30570115,  0.07681557, -0.51442047,  0.4152814 ,  0.31753911,
         -0.37188219],
        [-0.45749571, -0.17823889, -0.08098099, -0.34914665,  0.24894472,
          0.04343056,  0.42044872,  0.18817892,  0.11090776, -0.5801002

In [33]:
r

matrix([[-6.55743852,  2.5924757 , -0.45749571, -1.5249857 ,  3.81246426,
          1.82998284, -5.03245282, -4.26995997, -0.91499142, -0.91499142,
          1.5249857 ],
        [ 0.        , -6.65425201, -1.53075755,  1.96062782, -1.82083261,
          0.26211602, -0.15726961, -2.26468241, -0.80731734, -0.35647779,
          0.59412964],
        [ 0.        ,  0.        ,  5.95377855, -1.96453873, -0.0072336 ,
         -1.80751678,  3.93983965, -0.40649279, -1.789521  , -0.4978831 ,
          1.78158169],
        [ 0.        ,  0.        ,  0.        , -7.13939386, -1.03226101,
         -1.08214355,  0.92810454, -0.43841265, -1.63486101,  3.3160433 ,
         -3.17403704],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  4.25253686,
         -1.55897631, -0.26190715,  1.10521452,  3.36689249,  1.0014508 ,
         -1.64506282],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         -5.80636713, -1.54449186, -1.70871013, -0.5392686 ,  1.3747670

In [34]:
#Проверка
q.dot(r)

matrix([[ 0.00000000e+00, -1.00000000e+00, -2.00000000e+00,
         -3.00000000e+00,  1.00000000e+00, -1.00000000e+00,
         -2.00000000e+00, -1.47851911e-15,  1.00000000e+00,
          3.00000000e+00, -3.00000000e+00],
        [ 1.00000000e+00,  1.00000000e+00,  2.00000000e+00,
          3.00000000e+00,  1.00000000e+00, -1.00000000e+00,
         -1.00000000e+00,  2.00000000e+00,  1.00000000e+00,
          1.00000000e+00,  1.00000000e+00],
        [-2.00000000e+00,  3.00000000e+00, -1.00000000e+00,
         -5.93411155e-16, -9.75461709e-16, -3.96725880e-16,
         -2.00000000e+00, -3.00000000e+00, -2.00000000e+00,
         -1.00000000e+00,  1.00000000e+00],
        [-1.00000000e+00, -2.00000000e+00,  4.10454687e-16,
          1.00000000e+00, -2.00000000e+00,  2.00000000e+00,
         -1.00000000e+00,  1.82788673e-15,  7.74793273e-16,
         -2.00000000e+00, -7.35090182e-17],
        [ 3.00000000e+00, -2.00000000e+00,  3.60730476e-16,
          1.00000000e+00, -2.00000000e+00,  

# QR-разложение матриц с комплексными числами

In [35]:
#Вычислите QR-разложение своих матриц (действительной и комплексной из Задания 01). Проверьте правильность полученных результатов. 
A = np.matrix([[-3.-2.j, -3.+3.j,  0.-2.j, -1.+1.j,  1.-2.j,  2.-3.j, -2.+0.j,  2.-3.j, -3.+1.j,
  -3.-1.j,  1.+2.j],
 [ 2.+0.j,  1.-1.j, -2.+0.j,  0.-2.j,  0.+1.j,  0.-2.j,  2.+3.j,  1.+3.j,  0.-3.j,
  -1.+1.j,  2.-1.j],
 [ 3.-1.j, -2.-1.j,  3.+0.j, -2.+1.j,  1.+1.j, -1.-2.j, -3.+1.j,  1.+1.j,  3.+1.j,
  -2.-1.j,  1.+0.j],
 [ 2.+3.j,  3.-3.j, -3.-3.j,  0.+1.j, -3.-1.j,  3.+0.j,  1.+3.j,  1.-1.j, 0.-2.j,
   0.+2.j, -1.+2.j],
 [-2.+0.j,  0.-3.j,  1.-1.j,  0.-3.j,  3.-2.j, -1.+0.j,  0.-3.j, -1.+1.j, -3.-3.j,  
  -1.+2.j, -2.+0.j],
 [-3.+0.j,  2.+3.j, 2.-1.j,  1.-2.j,  1.+2.j,  0.-1.j, -1.+0.j, -2.+0.j,  0.+2.j,
   2.+0.j,  3.+3.j],
 [ 0.+0.j,  0.+2.j,  2.+0.j,  2.+1.j,  1.-1.j, -1.+3.j,  0.-2.j, -1.+2.j,  2.-3.j,
  -3.+0.j, -3.+3.j],
 [-2.-1.j, -3.+1.j,  2.+1.j, -1.-1.j,  0.+1.j, -1.+1.j, -2.+2.j,  3.+1.j,  0.-3.j,
   0.+2.j,  0.-2.j],
 [-2.+2.j, -3.-2.j,  3.+3.j, -1.-2.j, -3.+3.j, -3.+2.j, -2.+3.j,  0.+3.j,  2.-2.j,
   2.+2.j,  2.-3.j],
 [-3.+1.j,  1.+0.j, -3.+1.j,  2.-1.j,  2.+3.j,  0.+1.j, -3.+0.j, -3.+0.j,  2.+3.j,
   2.+3.j, -2.+2.j],
 [ 2.+3.j,  3.+2.j, -1.+2.j,  3.+3.j,  1.-2.j,  1.+2.j,  0.-3.j, -1.+0.j, -2.+2.j,
   1.+3.j,  2.+3.j]])
q, r = np.linalg.qr(A)
A

matrix([[-3.-2.j, -3.+3.j,  0.-2.j, -1.+1.j,  1.-2.j,  2.-3.j, -2.+0.j,
          2.-3.j, -3.+1.j, -3.-1.j,  1.+2.j],
        [ 2.+0.j,  1.-1.j, -2.+0.j,  0.-2.j,  0.+1.j,  0.-2.j,  2.+3.j,
          1.+3.j,  0.-3.j, -1.+1.j,  2.-1.j],
        [ 3.-1.j, -2.-1.j,  3.+0.j, -2.+1.j,  1.+1.j, -1.-2.j, -3.+1.j,
          1.+1.j,  3.+1.j, -2.-1.j,  1.+0.j],
        [ 2.+3.j,  3.-3.j, -3.-3.j,  0.+1.j, -3.-1.j,  3.+0.j,  1.+3.j,
          1.-1.j,  0.-2.j,  0.+2.j, -1.+2.j],
        [-2.+0.j,  0.-3.j,  1.-1.j,  0.-3.j,  3.-2.j, -1.+0.j,  0.-3.j,
         -1.+1.j, -3.-3.j, -1.+2.j, -2.+0.j],
        [-3.+0.j,  2.+3.j,  2.-1.j,  1.-2.j,  1.+2.j,  0.-1.j, -1.+0.j,
         -2.+0.j,  0.+2.j,  2.+0.j,  3.+3.j],
        [ 0.+0.j,  0.+2.j,  2.+0.j,  2.+1.j,  1.-1.j, -1.+3.j,  0.-2.j,
         -1.+2.j,  2.-3.j, -3.+0.j, -3.+3.j],
        [-2.-1.j, -3.+1.j,  2.+1.j, -1.-1.j,  0.+1.j, -1.+1.j, -2.+2.j,
          3.+1.j,  0.-3.j,  0.+2.j,  0.-2.j],
        [-2.+2.j, -3.-2.j,  3.+3.j, -1.-2.j, -3.+3.j, -3

In [36]:
q

matrix([[-3.17999364e-01-2.11999576e-01j,
          1.98057233e-01-1.90811237e-01j,
          1.61224106e-01+1.84234060e-01j,
         -2.73839874e-02+3.97856446e-02j,
         -5.50850493e-02+2.94433026e-01j,
         -3.60725937e-01+4.65001025e-01j,
          4.81128412e-03-5.45860546e-02j,
         -2.90057068e-01-1.39397198e-01j,
          1.58246678e-01+2.57592878e-01j,
          1.64805140e-01+6.55839285e-02j,
         -6.68435197e-02-2.14617967e-01j],
        [ 2.11999576e-01-7.43963956e-20j,
         -9.05749542e-02+8.45366239e-03j,
          1.92465137e-01+1.44700179e-02j,
          1.12453248e-01+5.28773833e-01j,
         -2.53483673e-03-8.34926645e-02j,
          3.09411279e-01+2.11093351e-02j,
         -6.29979206e-02-1.81293233e-01j,
         -2.34447689e-01-3.76035859e-01j,
         -1.77897390e-01+3.87590959e-02j,
          3.74405478e-01-2.06590373e-02j,
          3.23340277e-01-5.11193502e-02j],
        [ 3.17999364e-01-1.05999788e-01j,
          1.90811237e-01-4.95143

In [37]:
r

matrix([[ 9.43398113+0.00000000e+00j,  0.74199852-4.34599131e+00j,
         -0.52999894+1.27199746e+00j,  0.31799936+1.16599767e+00j,
         -1.16599767-1.05999788e-01j,  2.86199428-7.41998516e-01j,
          2.75599449-1.98805509e-16j,  1.8019964 +1.80199640e+00j,
          0.95399809-8.47998304e-01j,  1.27199746-2.75599449e+00j,
          1.27199746-5.29998940e-01j],
        [ 0.        +0.00000000e+00j, -9.30385929+0.00000000e+00j,
          2.80299292+1.89603571e+00j, -4.92606984+6.71462327e-01j,
          0.17148858+2.02646364e+00j, -1.46731426+1.17022841e+00j,
         -0.42509845+1.82478341e+00j,  3.27881334+1.20042006e+00j,
         -1.46248359-1.87912838e+00j,  0.95888685-1.45282227e+00j,
         -2.2305592 -1.49025991e+00j],
        [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         -8.40531992+0.00000000e+00j,  0.5686856 +2.87908572e+00j,
         -1.68868352-3.69487352e-01j,  0.43368358-2.63939613e+00j,
          2.47553128-4.26487177e-01j, -1.45103239-3

In [38]:
#Проверка
q.dot(r)

matrix([[-3.00000000e+00-2.00000000e+00j,
         -3.00000000e+00+3.00000000e+00j,
          1.22124533e-15-2.00000000e+00j,
         -1.00000000e+00+1.00000000e+00j,
          1.00000000e+00-2.00000000e+00j,
          2.00000000e+00-3.00000000e+00j,
         -2.00000000e+00-6.10622664e-16j,
          2.00000000e+00-3.00000000e+00j,
         -3.00000000e+00+1.00000000e+00j,
         -3.00000000e+00-1.00000000e+00j,
          1.00000000e+00+2.00000000e+00j],
        [ 2.00000000e+00-7.01854192e-19j,
          1.00000000e+00-1.00000000e+00j,
         -2.00000000e+00-7.35522754e-16j,
          1.63757896e-15-2.00000000e+00j,
          1.11022302e-16+1.00000000e+00j,
         -4.44089210e-16-2.00000000e+00j,
          2.00000000e+00+3.00000000e+00j,
          1.00000000e+00+3.00000000e+00j,
         -1.11022302e-15-3.00000000e+00j,
         -1.00000000e+00+1.00000000e+00j,
          2.00000000e+00-1.00000000e+00j],
        [ 3.00000000e+00-1.00000000e+00j,
         -2.00000000e+00-1.00000

# Сингулярное разложение матрицы с действительными числами 

In [65]:
A = np. array([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
 [ 1,  1,  2,  3,  1, -1, -1,  2, 1,  1,  1],
 [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
 [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
 [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
 [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
 [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
 [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
 [-3, 1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
 [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
 [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])

In [66]:
Z, D, E = np. linalg.svd(A)

In [67]:
Z

array([[ 0.0541015 , -0.3600328 ,  0.40563698,  0.34480481,  0.14643356,
         0.1078805 , -0.32621209, -0.21188412,  0.20709486, -0.16686635,
         0.57349354],
       [-0.04425902,  0.10530986,  0.13819373, -0.31980584, -0.14764698,
        -0.63463478, -0.1296255 ,  0.32992246,  0.4217515 ,  0.23561119,
         0.28631834],
       [ 0.37954363, -0.05430105, -0.20570499,  0.08777383, -0.02358139,
        -0.11308919,  0.69541536, -0.16747939, -0.08653672,  0.20951663,
         0.47602133],
       [ 0.03799358,  0.28105666, -0.05169741,  0.14133815,  0.1000159 ,
         0.29807815,  0.02834731,  0.77850595, -0.15666602, -0.23255168,
         0.33550137],
       [-0.36274352,  0.28162998,  0.0531974 , -0.0460275 , -0.10644376,
         0.5650167 ,  0.0934155 , -0.11111272,  0.37890463,  0.51686456,
         0.14761051],
       [-0.36538961,  0.29635952,  0.19590705, -0.4271563 , -0.20830599,
        -0.02510783,  0.1134621 , -0.3061913 , -0.31802737, -0.4403779 ,
         0.334

In [68]:
D

array([11.38049224, 10.10939491,  9.13515909,  7.98700805,  6.67080492,
        5.48368381,  4.36875224,  3.12201062,  2.32519406,  1.0807706 ,
        0.25126946])

In [69]:
E

array([[-5.30316685e-01,  2.71053004e-01, -1.68541299e-01,
         6.79272809e-03,  3.65534877e-01,  2.10069214e-01,
        -5.41371047e-01, -3.42360326e-01,  3.32895004e-02,
        -1.03471270e-01,  1.30344368e-01],
       [ 1.08269809e-01, -3.29461623e-01, -2.15606852e-01,
         6.86452666e-01, -1.28431906e-01,  3.19342403e-01,
        -6.49844373e-03,  1.88565766e-03,  1.21434579e-01,
        -3.51079801e-01,  3.24816281e-01],
       [ 1.57234231e-01, -6.65872500e-03, -3.84309127e-01,
         1.83010437e-01,  1.25685514e-01, -1.49814695e-01,
        -3.33227374e-01,  3.12095368e-01,  4.88037051e-01,
         1.46792347e-01, -5.36314538e-01],
       [-5.56923783e-02, -5.77030926e-01, -3.34161472e-01,
        -1.06537782e-01, -3.14426843e-01, -1.77921339e-01,
        -2.43949204e-01, -4.22835459e-01, -3.05634940e-01,
         2.45653878e-01, -1.35423981e-01],
       [ 5.14780648e-02,  1.33954524e-01, -3.30424602e-01,
        -2.48751458e-01, -2.42368765e-01,  6.45137430e-01,
  

# Сингулярное разложение матрицы с комплексными числами¶

In [50]:

A = np. array([[-3.-2.j, -3.+3.j,  0.-2.j, -1.+1.j,  1.-2.j,  2.-3.j, -2.+0.j,  2.-3.j, -3.+1.j,
  -3.-1.j,  1.+2.j],
 [ 2.+0.j,  1.-1.j, -2.+0.j,  0.-2.j,  0.+1.j,  0.-2.j,  2.+3.j,  1.+3.j,  0.-3.j,
  -1.+1.j,  2.-1.j],
 [ 3.-1.j, -2.-1.j,  3.+0.j, -2.+1.j,  1.+1.j, -1.-2.j, -3.+1.j,  1.+1.j,  3.+1.j,
  -2.-1.j,  1.+0.j],
 [ 2.+3.j,  3.-3.j, -3.-3.j,  0.+1.j, -3.-1.j,  3.+0.j,  1.+3.j,  1.-1.j, 0.-2.j,
   0.+2.j, -1.+2.j],
 [-2.+0.j,  0.-3.j,  1.-1.j,  0.-3.j,  3.-2.j, -1.+0.j,  0.-3.j, -1.+1.j, -3.-3.j,  
  -1.+2.j, -2.+0.j],
 [-3.+0.j,  2.+3.j, 2.-1.j,  1.-2.j,  1.+2.j,  0.-1.j, -1.+0.j, -2.+0.j,  0.+2.j,
   2.+0.j,  3.+3.j],
 [ 0.+0.j,  0.+2.j,  2.+0.j,  2.+1.j,  1.-1.j, -1.+3.j,  0.-2.j, -1.+2.j,  2.-3.j,
  -3.+0.j, -3.+3.j],
 [-2.-1.j, -3.+1.j,  2.+1.j, -1.-1.j,  0.+1.j, -1.+1.j, -2.+2.j,  3.+1.j,  0.-3.j,
   0.+2.j,  0.-2.j],
 [-2.+2.j, -3.-2.j,  3.+3.j, -1.-2.j, -3.+3.j, -3.+2.j, -2.+3.j,  0.+3.j,  2.-2.j,
   2.+2.j,  2.-3.j],
 [-3.+1.j,  1.+0.j, -3.+1.j,  2.-1.j,  2.+3.j,  0.+1.j, -3.+0.j, -3.+0.j,  2.+3.j,
   2.+3.j, -2.+2.j],
 [ 2.+3.j,  3.+2.j, -1.+2.j,  3.+3.j,  1.-2.j,  1.+2.j,  0.-3.j, -1.+0.j, -2.+2.j,
   1.+3.j,  2.+3.j]])

In [60]:
Z, D, E = np. linalg.svd(A)

In [61]:
Z

array([[-0.34327711-0.1178797j , -0.11111381-0.2461663j ,
         0.48046026+0.17072713j, -0.11339904+0.15115035j,
         0.1042247 +0.07311777j, -0.10171112+0.25825382j,
         0.07038962+0.0489273j , -0.18797422+0.20504566j,
         0.06540753-0.31637343j,  0.3187184 -0.19868206j,
         0.16689994+0.21992688j],
       [ 0.2186938 -0.03391829j,  0.25543327+0.14755922j,
         0.05662157-0.09630466j,  0.19947286+0.21420456j,
         0.12593215+0.22576847j,  0.02268445+0.28240525j,
        -0.2371128 -0.0965771j , -0.15581801-0.04575974j,
        -0.57690588+0.11291906j,  0.28593042+0.18930068j,
        -0.09147764+0.23515617j],
       [ 0.22047268-0.09291125j, -0.10215639-0.13427905j,
         0.15241388+0.06334692j, -0.35197522+0.1740232j ,
        -0.23741704-0.09474488j, -0.02624183+0.13838687j,
        -0.52202877-0.06316535j,  0.44193713+0.33948795j,
         0.05813692+0.1832704j , -0.08702903+0.1053624j ,
         0.03992661+0.05826054j],
       [-0.0744179 +0.115074

In [62]:
D

array([16.50088102, 13.15741627, 11.56497055, 10.97170699,  9.09840627,
        8.08688271,  5.54641085,  4.24712257,  3.49109366,  0.94832727,
        0.64029111])

In [63]:
E

array([[ 0.16032563+0.j        , -0.09590383-0.40394008j,
         0.15130972+0.28428724j, -0.0581715 -0.29115223j,
        -0.10329883+0.1701612j , -0.13596419-0.04817641j,
        -0.12567574+0.21066263j,  0.00102385+0.36605355j,
         0.38601371-0.14111505j,  0.16824636-0.09653878j,
         0.25123008-0.29291276j],
       [ 0.53282076+0.j        ,  0.14578243-0.38992309j,
        -0.28716421-0.05938713j, -0.02153464+0.01676371j,
        -0.10032843-0.11019615j,  0.33088957-0.14324224j,
         0.37513687-0.0395123j ,  0.19586732-0.03645478j,
        -0.27623707-0.14061689j,  0.09299343-0.11279276j,
         0.06368725+0.0192733j ],
       [-0.11621489+0.j        , -0.14174358+0.10230234j,
         0.01656142-0.27921709j, -0.26355525-0.06873303j,
        -0.29207738-0.14737792j,  0.15964233-0.26388249j,
        -0.33647636+0.3912315j ,  0.28692571-0.1363575j ,
        -0.18602913+0.1872511j ,  0.03310088+0.02276652j,
         0.40196862-0.0361276j ],
       [-0.29938438+0.j     